// Code generated by 'goexports github.com/boombuler/barcode/qr'. DO NOT EDIT.

// +build go1.14,!go1.15

package main

import (
	"github.com/boombuler/barcode/qr"
	"reflect"
)

func init() {
	GotxSymbols["github.com/boombuler/barcode/qr"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AlphaNumeric": reflect.ValueOf(qr.AlphaNumeric),
		"Auto":         reflect.ValueOf(qr.Auto),
		"Encode":       reflect.ValueOf(qr.Encode),
		"H":            reflect.ValueOf(qr.H),
		"L":            reflect.ValueOf(qr.L),
		"M":            reflect.ValueOf(qr.M),
		"Numeric":      reflect.ValueOf(qr.Numeric),
		"Q":            reflect.ValueOf(qr.Q),
		"Unicode":      reflect.ValueOf(qr.Unicode),

		// type definitions
		"Encoding":             reflect.ValueOf((*qr.Encoding)(nil)),
		"ErrorCorrectionLevel": reflect.ValueOf((*qr.ErrorCorrectionLevel)(nil)),
	}
}
